### ISSUE TITLE
Part 4: Tracking Part 4 steps as given in the instructions

### ISSUE THREAD

**Issue by pranaypareek** [NYU-Shopcarts/shopcarts#59]
This is an umbrella issue including all the steps for Part-4 as given in the instructions. Some of the points are already checked as they were done with Part 1 & Part 2 due to overlaps.

- [x]  Create a free account on Travis CI.
- [x]  Create a .travis.yml file and configure Travis CI to run test cases every time someone pushes to the master branch or submits a Pull Request.
- [x]  Set up Travis CI to monitor your GitHub repository for push and pull requests.
- [x]  Add a Travis CI badge to your README.md file.
- [x]  Add Swagger docs to your service to document your API using flasgger or Flask-RESTPlus as shown in class. The documentation API must be at: /apidocs/index.html
- [x]  Set up the DevOps Pipeline in Bluemix to build and deploy your project when the master branch changes.
- [x]  Connect this DevOps pipeline to the GitHub repository for your project
- [x]  Your Pipeline must have 4 stages: Build, Dev, Test, Prod
- [x]  Add a Unit Test Stage to the pipeline to run your units tests with nosetests
- [x]  Add a Dev Deployment Stage to the pipeline to deploy to your Dev space if the unit tests pass
- [x]  Add a Integration Test Stage to the pipeline to run your integration tests with behave on the Dev deployment
- [x]  Create a new Space in your Cloud Foundry account called: Prod
- [x]  Add a Production Deploy Stage to the pipeline to deploy to production if all of the integration tests pass.
- [x]  (optional) Integrate your Pull Requests with your Slack channel so that any time someone makes a pull request, the channel is notified so someone can approve it.
- [ ]  Invite Professor to Bluemix Organization
